# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: development
  development:
    gas_limit: max
    gas_buffer: 1
    gas_price: 0
    reverting_tx_gas_limit: max
    default_contract_owner: true
    cmd_settings:
      port: 8545
      gas_limit: 6721975
      accounts: 500

  mainnet:
    gas_limit: 3000000
    gas_price: 86000000000
    cmd_settings:
      gas_limit: 3000000

  # in command line brownie networks add Ethereum mainnet-new host=$YOUR_ARCHIVE_NODE chainid=1, $YOUR_ARCHIVE_NODE = Alchemy NODE.
  # brownie console --network mainnet-fork
  
  mainnet-fork:
    chainid: 1
    gas_limit: max
    explorer: https://api.etherscan.io/api
    cmd_settings:
      fork: mainnet-test
      accounts: 10
      default_balance: 100
      gas_limit: 6721975

  rinkeby:
    gas_limit: max

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - iearn-finance/yearn-vaults@0.3.4
  - OpenZeppelin/openzeppelin-contracts@3.3.0
  - OpenZeppelin/openzeppelin-contracts-upgradeable@3.3.0
# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.6.12
    remappings:
      - "@yearnvaults=iearn-finance/yearn-vaults@0.3.4"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.3.0"
      - "@ozUpgradesV3=OpenZeppelin/openzeppelin-contracts-upgradeable@3.3.0"
    optimizer:
      runs: 99999

  vyper:
    version: 0.2.8

reports:
  exclude_contracts:
    - SafeMath